.TH "SMPCP.CONF" "5" "0.1.7" "October 2021" "SMPCP"
.SH "NAME"
smpcp.conf - configuration file documentation.
.SH "DESCRIPTION"
\fBsmpcp.conf\fR is the configuration file for \fBsmpcp(1)\fR. It must be located at \fB$XDG_CONFIG_HOME/smpcp\fR.
.PP
Each line of the file contains a setting name and its value, i.e:
.PP
.B resume_state = off
.PP
If a line starts by \fB#\fR, it is considered as a comment and is ignored by \fBsmpcp\fR.

Tilde in filesystem path is expanded.
.SH "MANDATORY SETTINGS"
.TP
.B sticker_db = <filepath>
  Path to the sticker database (i.e. \fB~/.config/mpd/sticker.sql\fR).
.SH "OPTIONAL SETTINGS"
.TP
.B music_directory = <path>
  Path to the music directory. May be necessary if the path cannot be directly retrieved from \fBMPD\fR. For instance when \fBMPD\fR is configured in satellite mode.
.TP
.B keep_in_history = <duration>
How long a song is kept in history. \fB<duration>\fR must be a string that can be read by the \fBdate(1)\fR command. For instance: 1 month, 2 weeks, 1 day (default: 2 weeks).
.br
If a song is in history, it is ignored when songs are added to the queue in \fIsong\fR mode.
.TP
.B skip_limit = <count>
Set the skip limit for songs. If a song skip count is greater or equal to this setting, it is discarded when adding songs in \fIsong\fR mode (default: 2).
.TP
.B status_format = <format>
Format used in status and notifications (see \fBsmpcp(1) OUTPUT FORMATTING section\fR) (default: [[%artist% - ]]%title%).
.TP
.B playlist_song_count = <count>
How many songs must be added to the queue in \fIsong\fR mode (default: 10).
.TP
.B song_mode_xfade_duration = <duration>
Crossfade duration in seconds for \fIsong\fR mode (default: 10).
.TP
.B resume_state = <on|off>
  If set to on, the queue and playback state is saved on shutdown and is restored on restart (default: off).
.TP
.B play_icon = <string>
.TP
.B pause_icon = <string>
.TP
.B stop_icon = <string>
  Playback state icons shown in status and notifications (default: [>, ||, [])
.SH "FILES"
.TP
.B $XDG_CONFIG_HOME/smpcp/smpcp.conf
  User configuration file (usually ~/.config/smpcp/smpcp.conf)
.TP
.B /etc/smpcp/smpcp.conf
  Default configuration file. Can be used as a starting point.
.SH "SEE ALSO"
.TP
.B smpcp(1)
.SH "AUTHOR"
.TP
Stéphane MEYER (teegre)
.SH "COPYRIGHT"
.TP
2021 Stéphane MEYER (teegre)
