#! /usr/bin/env bash

#
# .▄▄ · • ▌ ▄ ·.  ▄▄▄· ▄▄·  ▄▄▄· super
# ▐█ ▀. ·██ ▐███▪▐█ ▄█▐█ ▌▪▐█ ▄█ music
# ▄▀▀▀█▄▐█ ▌▐▌▐█· ██▀·██ ▄▄ ██▀· player
# ▐█▄▪▐███ ██▌▐█▌▐█▪·•▐███▌▐█▪·• client
#  ▀▀▀▀ ▀▀  █▪▀▀▀.▀   ·▀▀▀ .▀    plus+
#
# Copyright (C) 2021, Stéphane MEYER.
#
# Smpcp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
# SMPCP
# C │ 2021/04/04
# M │ 2021/04/13
# D │ Main program.

declare SMPCP_LIB="/usr/lib/smpcp"

source "$SMPCP_LIB"/client.sh
source "$SMPCP_LIB"/core.sh
source "$SMPCP_LIB"/player.sh
source "$SMPCP_LIB"/playlist.sh
source "$SMPCP_LIB"/query.sh
source "$SMPCP_LIB"/statistics.sh
source "$SMPCP_LIB"/volume.sh

__is_mpd_running || {
  __msg E "MPD is not running."
  exit 1
}

case $1 in
  add        ) shift; add "$@" ;;
  addalbum   ) shift; add_album "$@" ;;
  clear      ) cmd clear ;;
  cmd        ) shift; cmd "$@" ;;
  consume    ) shift; consume "$@" ;;
  crop       ) crop ;;
  delete     ) shift; delete "$@" ;;
  dim        ) dim ;;
  getcurrent ) shift; getcurrent "$@" ;;
  getduration) shift; getduration "$@" ;;
  getelapsed ) shift; getelapsed "$@" ;;
  getnext    ) shift; getnext "$@" ;;
  getstat    ) shift; get_stat "$@" ;;
  getsticker ) shift; get_sticker "$@" ;;
  idle       ) shift; cmd idle "$@" ;;
  idleloop   ) shift; cmd idleloop "$@" ;;
  fcmd       ) shift; fcmd "$@" ;;
  ls         ) list ;;
  move       ) shift; move "$@" ;;
  next       ) next ;;
  pause      ) shift; pause "$@" ;;
  play       ) shift; play "$@" ;;
  playalbum  ) shift; add_album -p "$@" ;;
  prev       ) previous ;;
  random     ) shift; random "$@";;
  rating     ) shift; rating "$@" ;;
  repeat     ) shift; repeat "$@" ;;
  replaygain ) shift; replaygain "$@" ;;
  search     ) shift; search "$@" ;;
  searchadd  ) shift; searchadd "$@" ;;
  seek       ) shift; seek "$@" ;;
  setsticker ) shift; set_sticker "$@" ;;
  single     ) shift; single "$@" ;;
  status     ) status ;;
  stop       ) stop ;;
  stop_after ) stop_after_current ;;
  toggle     ) shift; toggle "$@" ;;
  vol        ) shift; volume "$@" ;;
  xfade      ) shift; xfade "$@" ;;
  *          ) __msg E "invalid option '$1'."
esac
