#! /usr/bin/env bash

#
# .▄▄ · • ▌ ▄ ·.  ▄▄▄· ▄▄·  ▄▄▄· super
# ▐█ ▀. ·██ ▐███▪▐█ ▄█▐█ ▌▪▐█ ▄█ music
# ▄▀▀▀█▄▐█ ▌▐▌▐█· ██▀·██ ▄▄ ██▀· player
# ▐█▄▪▐███ ██▌▐█▌▐█▪·•▐███▌▐█▪·• client
#  ▀▀▀▀ ▀▀  █▪▀▀▀.▀   ·▀▀▀ .▀    plus+
#
# Copyright (C) 2021, Stéphane MEYER.
#
# Smpcp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
# SMPCP
# C │ 2021/04/04
# M │ 2021/04/16
# D │ Main program.

declare SMPCP_LIB="/usr/lib/smpcp"

# shellcheck source=/usr/lib/smpcp/client.sh
source "$SMPCP_LIB"/client.sh
# shellcheck source=/usr/lib/smpcp/core.sh
source "$SMPCP_LIB"/core.sh
# shellcheck source=/usr/lib/smpcp/help.sh
source "$SMPCP_LIB"/help.sh
# shellcheck source=/usr/lib/smpcp/player.sh
source "$SMPCP_LIB"/player.sh
# shellcheck source=/usr/lib/smpcp/playlist.sh
source "$SMPCP_LIB"/playlist.sh
# shellcheck source=/usr/lib/smpcp/query.sh
source "$SMPCP_LIB"/query.sh
# shellcheck source=/usr/lib/smpcp/statistics.sh
source "$SMPCP_LIB"/statistics.sh
# shellcheck source=/usr/lib/smpcp/volume.sh
source "$SMPCP_LIB"/volume.sh

__is_mpd_running || {
  __msg E "MPD is not running."
  exit 1
}

case $1 in
  add        ) shift; add "$@" ;;
  addalbum   ) shift; add_album "$@" ;;
  albuminfo  ) get_album_info ;;
  clear      ) cmd clear ;;
  cmd        ) shift; cmd "$@" ;;
  consume    ) shift; consume "$@" ;;
  crop       ) crop ;;
  delete     ) shift; delete "$@" ;;
  dim        ) dim ;;
  discog     ) shift; get_discography "$@" ;;
  getcurrent ) shift; get_current "$@" ;;
  getduration) shift; get_duration "$@" ;;
  getelapsed ) shift; get_elapsed "$@" ;;
  getnext    ) shift; get_next "$@" ;;
  getsticker ) shift; get_sticker "$@" ;;
  help       ) _help ;;
  idle       ) shift; cmd idle "$@" ;;
  idleloop   ) shift; cmd idleloop "$@" ;;
  insertalbum) shift; add_album -i "$@" ;;
  fcmd       ) shift; fcmd "$@" ;;
  ls         ) list_queue ;;
  move       ) shift; move "$@" ;;
  next       ) next ;;
  pause      ) shift; pause "$@" ;;
  play       ) shift; play "$@" ;;
  playalbum  ) shift; add_album -p "$@" ;;
  prev       ) previous ;;
  random     ) shift; random "$@";;
  rating     ) shift; rating "$@" ;;
  repeat     ) shift; repeat "$@" ;;
  replaygain ) shift; replaygain "$@" ;;
  search     ) shift; search "$@" ;;
  searchadd  ) shift; searchadd "$@" ;;
  seek       ) shift; seek "$@" ;;
  setsticker ) shift; set_sticker "$@" ;;
  single     ) shift; single "$@" ;;
  status     ) status ;;
  stop       ) stop ;;
  stop_after ) stop_after_current ;;
  toggle     ) shift; toggle "$@" ;;
  vol        ) shift; volume "$@" ;;
  xfade      ) shift; xfade "$@" ;;
  ""         ) _print_version; status ;;
  *          ) __msg E "invalid option '$1'."
esac
