#! /usr/bin/env bash

#
# .▄▄ · • ▌ ▄ ·.  ▄▄▄· ▄▄·  ▄▄▄· simple
# ▐█ ▀. ·██ ▐███▪▐█ ▄█▐█ ▌▪▐█ ▄█ music
# ▄▀▀▀█▄▐█ ▌▐▌▐█· ██▀·██ ▄▄ ██▀· player
# ▐█▄▪▐███ ██▌▐█▌▐█▪·•▐███▌▐█▪·• client
#  ▀▀▀▀ ▀▀  █▪▀▀▀.▀   ·▀▀▀ .▀    plus+
#
# This file is part of smpcp.
# Copyright (C) 2021, Stéphane MEYER.
#
# Smpcp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>
#
# TRACKER
# C : 2021/04/09
# M : 2021/04/10
# D : Notification and statistics update.


declare SMPCP_LIB="/usr/lib/smpcp"

source "$SMPCP_LIB"/client.sh
source "$SMPCP_LIB"/core.sh
source "$SMPCP_LIB"/player.sh
source "$SMPCP_LIB"/statistics.sh

declare _ID
declare _VERBOSE

__is_mpd_running || {
  __msg E "MPD is not running."
  exit 1
}

[[ $1 == "--verbose" || $1 == "-v" ]] && { _VERBOSE=1; shift; }

track() {
  # notify song change and
  # and update playback statistics.

  local s
  s="$(state -p)"

  [[ $s == "pause" || $s == "stop" ]] && return 1

  local duration elapsed uri
  # shellcheck disable=2119
  {
    duration="$(getduration)"
    elapsed="$(getelapsed)"
  }

  uri="$(getcurrent)"

  notify-send -i "$(get_albumart)" "$(status)"
  media_update

  _ID="$(getcurrent "%id%")"

  sleep $((duration-elapsed))

  update_stats "$uri"
}


track & pid=$!
wait_for_pid 1 "$pid" && unset pid
  
while read -r; do

  s="$(state -p)"

  # song changed.
  if [[ $(getcurrent "%id%") != "$_ID" ]] &&  ! wait_for_pid 2 "$pid"; then
    [[ $s == "play" ]] && {

      [[ $_VERBOSE ]] &&
        echo "change"

      kill "$pid" 2> /dev/null
      track & pid=$!
      continue
    }
  fi
  
  # pause/stop.
  [[ $s == "pause" || $s == "stop" ]] && {

    [[ $_VERBOSE ]] &&
      echo "$s"

    ! wait_for_pid 2 "$pid" && kill "$pid" 2> /dev/null
    unset pid
    media_update
    continue
  }
  
  wait $pid

  # song ended normally.
  [[ $s == "play" ]] && {

    [[ $_VERBOSE ]] &&
      echo "end"

    track & pid=$!
  }

done < <(cmd idleloop player)
